name: yalla_nemshi
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  shared_preferences: ^2.2.3
  google_maps_flutter: ^2.7.0
  http: ^1.1.0
  image_picker: ^1.1.1
  table_calendar: ^3.0.8
  flutter_local_notifications: ^19.5.0
  timezone: ^0.10.1
  pedometer: ^4.0.0
  permission_handler: ^11.3.0
  firebase_core: ^4.2.1
  firebase_auth: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0



flutter:
  uses-material-design: true

  assets:
    - assets/images/bg_minimal_dark.png
    - assets/images/bg_minimal_light.png
    - assets/images/walk_group.jpg
    

