name: yalla_nemshi
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  shared_preferences: ^2.2.3
  google_maps_flutter: ^2.7.0
  http: ^1.1.0
  image_picker: ^1.1.1
  table_calendar: ^3.0.8
  flutter_local_notifications: ^19.5.0
  timezone: ^0.10.1
  pedometer: ^4.0.0
  permission_handler: ^11.3.0
  geolocator: ^13.0.2
  firebase_core: ^4.2.1
  firebase_auth: ^6.1.2
  google_sign_in: ^6.2.1
  cloud_firestore: 6.1.0
  cloud_functions: ^6.0.4
  firebase_crashlytics: ^5.0.5
  firebase_storage: ^13.0.4
  firebase_messaging: ^16.0.4
  cached_network_image: ^3.3.1
  flutter_riverpod: ^2.4.0
  intl: ^0.19.0
  flutter_dotenv: ^5.1.0
  connectivity_plus: ^6.0.3
  path_provider: ^2.1.2
  share_plus: ^7.2.1
  pdf: ^3.11.0



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0



flutter:
  uses-material-design: true
  assets:
    - .env
  fonts:
    # Poppins - Headlines and bold text
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
    # Inter - Body and UI text
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
          weight: 400
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700
